# MoveIt-specific simulation settings
moveit_sim_hw_interface:
    joint_model_group: controllers_initial_group_
    joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
generic_hw_control_loop:
    loop_hz: 300
    cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
    joints:
        - Joint_1
        - Joint_2
        - Joint_3
        - Joint_4
        - Joint_5
        - Gripper
    sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
    
arm_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
        - Joint_1
        - Joint_2
        - Joint_3
        - Joint_4
        - Joint_5
    gains:
        Joint_1: { p: 12000, d: 50, i: 0.0, i_clamp: 10000 }
        Joint_2: { p: 30000, d: 100, i: 0.02, i_clamp: 10000 }
        Joint_3: { p: 18000, d: 50, i: 0.01, i_clamp: 1 }
        Joint_4: { p: 18000, d: 70, i: 0.01, i_clamp: 10000 }
        Joint_5: { p: 12000, d: 70, i: 0.01, i_clamp: 1 }

    constraints:
        goal_time: 2.0
    state_publish_rate: 25

gripper_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
        - Gripper

    gains:
        Gripper: { p: 10, d: 3.0, i: 0, i_clamp: 1 }

    state_publish_rate: 25

controller_list:
    - name: arm_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints:
        - Joint_1
        - Joint_2
        - Joint_3
        - Joint_4
        - Joint_5
    - name: gripper_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints:
        - Gripper